/// ATTENTION: The following models were auto-generated by the plugin "Json to Dart".
/// I simply copied the JSON output from the "playlists" api and the plugin did the rest

class ApiPlaylistsModel {
  ApiPlaylistsModel({
      this.href, 
      this.items, 
      this.limit, 
      this.next, 
      this.offset, 
      this.previous, 
      this.total,});

  ApiPlaylistsModel.fromJson(dynamic json) {
    href = json['href'];
    if (json['items'] != null) {
      items = [];
      json['items'].forEach((v) {
        items?.add(ApiPlaylistModel.fromJson(v));
      });
    }
    limit = json['limit'];
    next = json['next'];
    offset = json['offset'];
    previous = json['previous'];
    total = json['total'];
  }
  String? href;
  List<ApiPlaylistModel>? items;
  int? limit;
  dynamic next;
  int? offset;
  dynamic previous;
  int? total;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['href'] = href;
    if (items != null) {
      map['items'] = items?.map((v) => v.toJson()).toList();
    }
    map['limit'] = limit;
    map['next'] = next;
    map['offset'] = offset;
    map['previous'] = previous;
    map['total'] = total;
    return map;
  }

}

class ApiPlaylistModel {
  ApiPlaylistModel({
      this.collaborative, 
      this.description, 
      this.externalUrls, 
      this.href, 
      this.id, 
      this.images, 
      this.name, 
      this.owner, 
      this.primaryColor, 
      this.public, 
      this.snapshotId, 
      this.tracks, 
      this.type, 
      this.uri,});

  ApiPlaylistModel.fromJson(dynamic json) {
    collaborative = json['collaborative'];
    description = json['description'];
    externalUrls = json['external_urls'] != null ? ApiExternalUrlModel.fromJson(json['external_urls']) : null;
    href = json['href'];
    id = json['id'];
    if (json['images'] != null) {
      images = [];
      json['images'].forEach((v) {
        images?.add(ApiImageModel.fromJson(v));
      });
    }
    name = json['name'];
    owner = json['owner'] != null ? ApiOwnerModel.fromJson(json['owner']) : null;
    primaryColor = json['primary_color'];
    public = json['public'];
    snapshotId = json['snapshot_id'];
    tracks = json['tracks'] != null ? ApiPlaylistTracksModel.fromJson(json['tracks']) : null;
    type = json['type'];
    uri = json['uri'];
  }
  bool? collaborative;
  String? description;
  ApiExternalUrlModel? externalUrls;
  String? href;
  String? id;
  List<ApiImageModel>? images;
  String? name;
  ApiOwnerModel? owner;
  dynamic primaryColor;
  bool? public;
  String? snapshotId;
  ApiPlaylistTracksModel? tracks;
  String? type;
  String? uri;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['collaborative'] = collaborative;
    map['description'] = description;
    if (externalUrls != null) {
      map['external_urls'] = externalUrls?.toJson();
    }
    map['href'] = href;
    map['id'] = id;
    if (images != null) {
      map['images'] = images?.map((v) => v.toJson()).toList();
    }
    map['name'] = name;
    if (owner != null) {
      map['owner'] = owner?.toJson();
    }
    map['primary_color'] = primaryColor;
    map['public'] = public;
    map['snapshot_id'] = snapshotId;
    if (tracks != null) {
      map['tracks'] = tracks?.toJson();
    }
    map['type'] = type;
    map['uri'] = uri;
    return map;
  }

}

class ApiPlaylistTracksModel {
  ApiPlaylistTracksModel({
      this.href, 
      this.total,});

  ApiPlaylistTracksModel.fromJson(dynamic json) {
    href = json['href'];
    total = json['total'];
  }
  String? href;
  int? total;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['href'] = href;
    map['total'] = total;
    return map;
  }

}

class ApiOwnerModel {
  ApiOwnerModel({
      this.displayName, 
      this.externalUrls, 
      this.href, 
      this.id, 
      this.type, 
      this.uri,});

  ApiOwnerModel.fromJson(dynamic json) {
    displayName = json['display_name'];
    externalUrls = json['external_urls'] != null ? ApiExternalUrlModel.fromJson(json['external_urls']) : null;
    href = json['href'];
    id = json['id'];
    type = json['type'];
    uri = json['uri'];
  }
  String? displayName;
  ApiExternalUrlModel? externalUrls;
  String? href;
  String? id;
  String? type;
  String? uri;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['display_name'] = displayName;
    if (externalUrls != null) {
      map['external_urls'] = externalUrls?.toJson();
    }
    map['href'] = href;
    map['id'] = id;
    map['type'] = type;
    map['uri'] = uri;
    return map;
  }

}

class ApiExternalUrlModel {
  ApiExternalUrlModel({
      this.spotify,});

  ApiExternalUrlModel.fromJson(dynamic json) {
    spotify = json['spotify'];
  }
  String? spotify;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['spotify'] = spotify;
    return map;
  }

}

class ApiImageModel {
  ApiImageModel({
      this.height, 
      this.url, 
      this.width,});

  ApiImageModel.fromJson(dynamic json) {
    height = json['height'];
    url = json['url'];
    width = json['width'];
  }
  int? height;
  String? url;
  int? width;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['height'] = height;
    map['url'] = url;
    map['width'] = width;
    return map;
  }

}
